name: Publish to Homebrew Tap

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  homebrew-tap:
    name: Update Homebrew Tap Formula
    runs-on: macos-latest
    steps:
      # 1. Check out your code repo to read the tag
      - name: Checkout code_djinn
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # 2. Extract version from the tag (e.g. v1.2.3 → 1.2.3)
      - name: Set VERSION env var
        run: |
          version="${{ github.ref_name }}"
          version_number="${version#v}" # Removes 'v' prefix if it exists
          echo "VERSION=${version_number}" >> $GITHUB_ENV

      # 3. Download GitHub release tarball
      - name: Download GitHub release tarball
        run: |
          curl -sL \
            "https://github.com/phisanti/code_djinn/archive/refs/tags/v${{ env.VERSION }}.tar.gz" \
            -o code-djinn-${{ env.VERSION }}.tar.gz

      # 4. Compute its SHA256 checksum
      - name: Compute sha256
        run: |
          echo "SHA256=$(shasum -a 256 code-djinn-${{ env.VERSION }}.tar.gz \
            | awk '{print $1}')" >> $GITHUB_ENV

      # 5. Check out your Homebrew tap repo
      - name: Checkout homebrew-code-djinn tap
        uses: actions/checkout@v5
        with:
          repository: phisanti/homebrew-code-djinn
          token: ${{ secrets.HOMEBREW_TOKEN }}
          path: homebrew-tap
          fetch-depth: 1

      # 6. Generate or update the formula file
      - name: Generate code-djinn formula
        run: |
          mkdir -p homebrew-tap/Formula
          cat > homebrew-tap/Formula/code-djinn.rb <<EOF
          class CodeDjinn < Formula
            include Language::Python::Virtualenv

            desc "AI-powered coding assistant that generates shell commands"
            homepage "https://github.com/phisanti/code_djinn"
            url "https://github.com/phisanti/code_djinn/archive/refs/tags/v${{ env.VERSION }}.tar.gz"
            sha256 "${{ env.SHA256 }}"
            license "MIT"

            depends_on "python@3.11"

            def install
              virtualenv_install_with_resources
            end

            test do
              system bin/"code_djinn", "--version"
            end
          end
          EOF

      # 7. Commit and push back to the tap
      - name: Commit & push formula update
        run: |
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/code-djinn.rb
          git commit -m "code-djinn: bump to v${{ env.VERSION }}" || echo "No changes to commit"
          git push origin HEAD:main